### ISSUE TITLE
Exception when querying providers on Windows integrated graphics

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/post-rs#82] opened 2023-06-13 19:04 UTC
There is a crash in OpenCL.dll when querying properties of an openCL platform that happens on some systems (for example by calling `scrypt_ocl::get_providers_count()`).

It was narrowed down to Intel's integrated graphics (both Intel HD and Intel Iris). Disabling the driver (leaving Nvidia enabled) resolves the issue.

An issue in the `ocl` library tracking the same: https://github.com/cogciprocate/ocl/issues/219.

Please see the logs.

[spacemesh-log-7f8f332c.txt](https://github.com/spacemeshos/post-rs/files/11738200/spacemesh-log-7f8f332c.txt)

https://spacemesh.sentry.io/issues/4234116670/?project=6324919&query=is%3Aunresolved&referrer=issue-stream&stream_index=0 that's the report in sentry about that exact issue.

**Comment by poszu** [comment] 2023-06-28 13:19
## Rootcause
The issue is caused by [opencl-intel-cpu-runtime](https://community.chocolatey.org/packages/opencl-intel-cpu-runtime), not the Intel GPU driver itself. The package installs an `intelopencl64.dll` in the C:\Windows\System32 directory and adds an entry in `HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors` Windows registry pointing to that file. I suspect that this dll is loaded for the Intel GPU platform and it is not compatible, leading to a crash.

## Steps to fix it
1. uninstall opencl-intel-cpu-runtime: `choco uninstall opencl-intel-cpu-runtime`
2. open Windows Registry Editor - hit `Win + r`
3. navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors
4. remove intelopencl64.dll entry
5. restart smapp / go-spacemesh.exe

**Comment by poszu** [comment] 2023-07-03 10:56
Moving to on hold as I'm waiting for the feedback from the user that reported this issue.

**Comment by poszu** [comment] 2023-08-02 07:22
Closing as there are no more reports of this crash. Reopen if the issue reappears.

**Closed by poszu** 2023-08-02 07:22 UTC
Labels: bug, milestone/genesis
